### ISSUE TITLE
env file created outside program folder on exit

### ISSUE THREAD

**Issue by shnbwmn** [turtletooth/OpenToonzPortable#5] opened 2016-08-08 14:29 UTC
When I exit OpenToonz Portable, a folder is created at the root of the drive:

`X:\stuff\profiles\env\myusername.env`

There is a corresponding `stuff\profiles` directory within the program folder; couldn't this ENV file be placed there rather?

**Comment by turtletooth** [comment] 2016-08-09 06:11
Thanks @shnbwmn - I noticed this yesterday too.  It is not an intended behavior.  I'll look into it.

**Comment by turtletooth** [comment] 2016-12-02 05:24
Fixed in 1.1.2 Portable

**Closed by turtletooth** 2016-12-02 05:24 UTC
